# Generated by Django 6.0.2 on 2026-02-07 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='send_to_all',
        ),
        migrations.AddField(
            model_name='document',
            name='target',
            field=models.CharField(choices=[('department', 'Department'), ('all_students', 'All Students'), ('single_student', 'Single Student')], default='department', max_length=20),
            preserve_default=False,
        ),
    ]
