# Generated by Django 6.0.2 on 2026-02-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='is_responded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='sender_type',
            field=models.CharField(max_length=20),
        ),
    ]
